# -*- coding: utf-8 -*-
"""sliitc lab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WfUP0YbMUbDZEUIIXMWeTrvczH1fG4jT
"""

student_name = input("Enter student name: ").title()
student_course = input("Enter student course: ").lower()
total_classes = int(input("Enter total classes held: "))
attended_classes = int(input("Enter classes attended: "))

if attended_classes > total_classes:
    print("Error: Attended classes cannot be more than total classes.")
else:
    attendance_percentage = (attended_classes / total_classes) * 100

    print("Student Name:", student_name)
    print("Course:", student_course)
    print("Attendance:", attendance_percentage, "%")

    if attendance_percentage >= 75:
        print("Allowed for exam")
    else:
        print("Not allowed for exam")